name: es_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  shared_preferences: ^2.0.7
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_storage: ^11.7.1
  image_picker: ^0.8.1
  flutter:
    sdk: flutter
  google_maps_flutter: 2.6.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  geolocator: ^11.0.0

  mockito: ^5.4.4
  fake_cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true
